spring:
  application:
    name: demo

  datasource:
    username: postgres
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://localhost:5432/test
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  security:
    user:
      name: admin
      password: admin